// presets.js - named experiments of the lab guide (chapters/08-lab.qmd "Suggested experiments" and the "Try it" boxes of
// chapters 4, 5 and 7), each as a URL-hash string in the encoding of state.js (keys in SCHEMA order, only non-default values
// except the field panels `f`, which are always spelled out so a preset looks the same whatever the performance preset).
//
//   hash  : the fragment without the leading '#'   (location.hash = '#' + hash loads the experiment)
//   note  : one line shown as the tooltip of the select entry
//
// Encoding reminders: slots `f` = kind.sub.cmap.log joined by '_' (trailing dots dropped); lists (`se`) and vectors (`k1`, `k2`)
// are joined by '_'; `v` = visible sections (f fields, s spectra, l Legendre lab, p PDFs, k kernels, e explain).
// Defaults: 2D, 256², Gaussian IC (seed 1), order 2, D = 0.3, nu = 1e-4; D_sc = 0.457 (order 1) / 0.428 (order 2) for that field.

export const PRESETS = [
  {
    id: 'zel-hc',
    title: 'Zel’dovich equals Hopf–Cole',
    hash: 'o=1&nu=0.00001&f=sheetgpu.density_hc_fabs.sheet_fabs.hc&se=lin_sheet_hc',
    note: 'Order 1, small ν, D below D_sc: the sheet and Hopf–Cole density panels and their spectra agree to the rasterization noise.',
  },
  {
    id: 'shell-crossing',
    title: 'Shell crossing',
    hash: 'D=0.7&o=1&f=sheetgpu.wire_sheetgpu.density_hc_hcdual',
    note: 'Order 1, D past D_sc: the sheet folds (wireframe, three-stream regions) while Hopf–Cole forms thin shocks of width ~√(νD).',
  },
  {
    id: 'orders-2',
    title: 'Higher orders: 2LPT',
    hash: 'D=0.35&hs=lpt&f=sheetgpu.density_hc_lptsrc.2_invj',
    note: 'Order 2 at D = 0.35: filaments sharpen, voids empty; Hopf–Cole sourced by the 2LPT potential, with ∇·Ψ⁽²⁾ and 1/J on the Lagrangian grid.',
  },
  {
    id: 'orders-4',
    title: 'Higher orders: 4LPT',
    hash: 'D=0.35&o=4&hs=lpt&f=sheetgpu.density_hc_lptsrc.4_invj',
    note: 'The same field at order 4: little changes before shell crossing; the order-4 source map shows where the series works hardest.',
  },
  {
    id: 'waves-harmonics',
    title: 'Two plane waves: harmonics',
    hash: 'ic=w&D=0.4&f=sheetgpu.both_hc_fabs.sheet_fphase.sheet',
    note: 'Two plane waves: |δ̂| and phase maps of the sheet show the harmonics 2k₁, 2k₂, k₁±k₂ generated by mode coupling.',
  },
  {
    id: 'kernels-viscous',
    title: 'Kernels: viscous vs gravity',
    hash: 'ic=w&D=0.2&nu=0.003&v=fk&f=sheetgpu.density_hc_fabs.sheet_fabs.hc&kx=nu',
    note: 'Kernels section, sweep over ν: the Hopf–Cole kernel follows the viscous F₂^ν (damping e^{−νk²D}), the 2LPT sheet the gravitational F₂ with its tidal term.',
  },
  {
    id: 'kernels-parallel',
    title: 'Kernels: parallel waves',
    hash: 'ic=w&k2=3_0_0&D=0.2&v=fk&f=sheetgpu.density_hc_fabs.sheet_fabs.hc',
    note: 'k₂ parallel to k₁: the tidal term switches off and the gravitational and Zel’dovich kernels agree.',
  },
  {
    id: 'loop-cutoff',
    title: 'The loop and the cutoff',
    hash: 'o=4&v=s&se=lin_sheet_hc_spt_eft_p22_p13',
    note: 'Gaussian field, order 4, D = 0.3: P(k) against the 1-loop SPT curve, P22 and |P13|, and the EFT fit with its fitted c_s².',
  },
  {
    id: 'legendre',
    title: 'Legendre lab',
    hash: 'hs=lpt&v=fl',
    note: 'Order 2, D < D_sc: the nLPT Legendre-transform density differs from the sheet only by rasterization noise; the Zel’dovich Hopf–Cole density by the genuine 2LPT correction.',
  },
  {
    id: 'pdfs',
    title: 'PDFs',
    hash: 'D=0.5&v=p',
    note: 'One-point distributions of log₁₀(1+δ) for every method at D = 0.5, at the grid scale and in top-hat discs.',
  },
  {
    id: 'phases',
    title: 'Phases: phase-only reconstruction and phase sums',
    hash: 'D=0.8&f=sheetgpu.density_hc_fphaseonly.sheet_fphaseonly.hc&se=lin_sheet_hc',
    note: 'Phase-only reconstructions of the sheet and Hopf–Cole density trace the walls and nodes of the web; the phase-sum plot shows ⟨cos θ⟩ growing as the web forms.',
  },
  {
    id: 'adhesion-web-1',
    title: 'Adhesion web: ν = 10⁻⁵ (sharp shocks)',
    hash: 'D=0.91&o=1&nu=0.00001&f=hc_hcdual_speed_sheetgpu.density',
    note: 'Order 1 at D = 2 D_sc: pancakes and filaments of the adhesion model; shock width below one cell, the density gets noisy.',
  },
  {
    id: 'adhesion-web-2',
    title: 'Adhesion web: ν = 10⁻⁴',
    hash: 'D=0.91&o=1&f=hc_hcdual_speed_sheetgpu.density',
    note: 'Order 1 at D = 2 D_sc, the default viscosity: shocks about 0.01 box wide.',
  },
  {
    id: 'adhesion-web-3',
    title: 'Adhesion web: ν = 10⁻³ (thick shocks)',
    hash: 'D=0.91&o=1&nu=0.001&f=hc_hcdual_speed_sheetgpu.density',
    note: 'Order 1 at D = 2 D_sc with ten times the viscosity: shocks thicken as √(νD) and the web softens.',
  },
  {
    id: '3d-one-loop',
    title: '3D one loop',
    hash: 'm=3&n=64&o=4&v=s&se=lin_cic_hc_spt_eft',
    note: '3D, 64³, order 4: the measured P(k) of CIC and Hopf–Cole against linear theory, 1-loop SPT and the EFT fit.',
  },
];
